<?php include APP_PATH . '/views/partials/inventory-tabs.php'; $totalUnits=array_sum(array_map(fn($item)=>(int)$item['quantity'],$items)); ?>
<div class="page-head grn-detail-head no-print"><div><div class="section-kicker">Posted delivery</div><h1><?= e($grn['grn_number']) ?></h1><p class="lede"><?= e($grn['supplier']) ?> · <?= e(date('d M Y, h:i A',strtotime($grn['created_at']))) ?></p></div><div class="page-actions"><a class="btn btn-ghost" href="<?= e(url('grn')) ?>">Goods received</a><button class="btn btn-outline" type="button" onclick="window.print()">Print / save PDF</button><a class="btn btn-primary" href="<?= e(url('grn/new').query_string(['supplier'=>$grn['supplier_id']?:'', 'supplier_name'=>$grn['supplier_id']?'':$grn['supplier']])) ?>">Receive another</a></div></div>

<article class="grn-document">
    <header class="grn-document-title"><div><div class="brand-lockup"><?= brand_logo(30) ?></div><span>Goods received note</span><h2><?= e($grn['grn_number']) ?></h2></div><span class="badge badge-green">Posted</span></header>
    <section class="grn-party-grid"><div><span>Supplier</span><h3><?= e($grn['supplier']) ?></h3><?php if($grn['supplier_contact']): ?><p><?= e($grn['supplier_contact']) ?></p><?php endif; ?><?php if($grn['supplier_phone']): ?><p><?= e($grn['supplier_phone']) ?></p><?php endif; ?><?php if($grn['supplier_email']): ?><p><?= e($grn['supplier_email']) ?></p><?php endif; ?><?php if($grn['supplier_address']): ?><p><?= e($grn['supplier_address']) ?></p><?php endif; ?></div><dl><div><dt>Supplier reference</dt><dd><?= e($grn['supplier_reference']?:'Not provided') ?></dd></div><div><dt>Received by</dt><dd><?= e($grn['user_name']??'System') ?></dd></div><div><dt>Posted</dt><dd><?= e(date('d M Y · h:i A',strtotime($grn['created_at']))) ?></dd></div><div><dt>Total units</dt><dd><?= number_format($totalUnits) ?></dd></div></dl></section>
    <div class="table-wrap grn-detail-table-wrap"><table class="table grn-detail-table"><thead><tr><th>Product</th><th class="num">Quantity</th><th class="num">Unit cost</th><th class="num">Line total</th></tr></thead><tbody><?php foreach($items as $item): $serials=$serialsByItem[(int)$item['id']]??[]; ?><tr><td><a class="cell-main" href="<?= e(url('products/'.$item['product_id'])) ?>"><?= e($item['product_name']) ?></a><span class="cell-sub"><?= e($item['sku']) ?> · <?= $item['is_serialized']?'Serial / IMEI':'Quantity tracked' ?></span><?php if($serials): ?><details class="grn-detail-serials"><summary><?= count($serials) ?> received serials</summary><div><?php foreach($serials as $serial): ?><span><code><?= e($serial['serial_number']) ?></code><?php if($serial['warranty_expires']): ?><small>Warranty to <?= e(date('d M Y',strtotime($serial['warranty_expires']))) ?></small><?php endif; ?></span><?php endforeach; ?></div></details><?php endif; ?></td><td class="num"><?= number_format($item['quantity']) ?></td><td class="num"><?= money($item['unit_cost']) ?></td><td class="num"><strong><?= money($item['unit_cost']*$item['quantity']) ?></strong></td></tr><?php endforeach; ?></tbody><tfoot><tr><td colspan="3">Total purchase cost</td><td class="num"><strong><?= money($grn['total_cost']) ?></strong></td></tr></tfoot></table></div>
    <?php if($grn['note']): ?><section class="grn-document-note"><span>Receiving note</span><p><?= nl2br(e($grn['note'])) ?></p></section><?php endif; ?>
    <footer><span><?= e($grn['grn_number']) ?></span><span>Stock posted to inventory</span><span><?= e(date('d M Y',strtotime($grn['created_at']))) ?></span></footer>
</article>
